# Generated by Django 4.1.7 on 2023-03-27 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0005_alter_playlist_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TvShowProxy',
            fields=[
            ],
            options={
                'verbose_name': 'TvShow',
                'verbose_name_plural': 'TvShows',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('playlists.playlist',),
        ),
        migrations.CreateModel(
            name='TvShowSeasonProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Season',
                'verbose_name_plural': 'Seasons',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('playlists.playlist',),
        ),
    ]
