# Generated by Django 4.1.7 on 2023-03-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0006_tvshowproxy_tvshowseasonproxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='type',
            field=models.CharField(choices=[('MV', 'Movie'), ('SW', 'Show'), ('SE', 'Season'), ('PLY', 'Playlist')], default='PLY', max_length=255),
        ),
    ]
