# Generated by Django 4.1.7 on 2023-03-27 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0008_alter_playlist_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('playlists.playlist',),
        ),
    ]
