# Generated by Django 4.1.7 on 2023-04-15 14:39

from django.db import migrations, models
import django.db.models.deletion
import playlists.models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0013_playlistrelated_playlist_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistrelated',
            name='related',
            field=models.ForeignKey(limit_choices_to=playlists.models.pr_limit_choices_to, on_delete=django.db.models.deletion.CASCADE, related_name='related_item', to='playlists.playlist'),
        ),
    ]
